-- Script SQL consolidado para crear tablas faltantes en Supabase
-- Copiar y pegar este contenido en el Editor SQL de Supabase (Dashboard -> SQL Editor)

-- ============================================================================
-- 1. Tabla lsd_rules_config (Robot de Actualizaciones LSD)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.lsd_rules_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL,
    config_json JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    active BOOLEAN DEFAULT true
);

-- Habilitar RLS
ALTER TABLE public.lsd_rules_config ENABLE ROW LEVEL SECURITY;

-- Política de lectura pública (necesaria para que la app descargue las reglas)
DROP POLICY IF EXISTS "Public Read Access" ON public.lsd_rules_config;
CREATE POLICY "Public Read Access" 
ON public.lsd_rules_config 
FOR SELECT 
USING (true);

-- Política de escritura (restringida, aunque con Service Role Key se ignora RLS)
DROP POLICY IF EXISTS "Admin Write Access" ON public.lsd_rules_config;
CREATE POLICY "Admin Write Access" 
ON public.lsd_rules_config 
FOR INSERT 
WITH CHECK (true);

-- Insertar datos iniciales si la tabla está vacía
INSERT INTO public.lsd_rules_config (version, config_json)
SELECT 
    20260101,
    '{
        "version": 20260101,
        "topes": {
            "min": 150000.00,
            "max": 2500000.00
        },
        "mensaje": "Reglas iniciales Enero 2026",
        "reglas_activas": ["base4_vs_base8", "cuil_mod11", "aportes_diff"]
    }'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.lsd_rules_config);


-- ============================================================================
-- 2. Tabla ocr_usage_logs (Control de Cuotas Freemium OCR)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.ocr_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL, -- Referencia al usuario autenticado
    scan_type TEXT DEFAULT 'ocr_vision',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.ocr_usage_logs ENABLE ROW LEVEL SECURITY;

-- Política: Los usuarios pueden ver su propio historial
DROP POLICY IF EXISTS "Users view own logs" ON public.ocr_usage_logs;
CREATE POLICY "Users view own logs" 
ON public.ocr_usage_logs 
FOR SELECT 
USING (auth.uid() = user_id);

-- Política: Los usuarios pueden insertar registros (al escanear)
DROP POLICY IF EXISTS "Users insert logs" ON public.ocr_usage_logs;
CREATE POLICY "Users insert logs" 
ON public.ocr_usage_logs 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- 3. Perfiles (roles y trial) - RLS por usuario
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY,
  trial_ends_at TIMESTAMP WITH TIME ZONE,
  user_role TEXT,
  updated_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE IF EXISTS public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Profiles: users read own" ON public.profiles;
CREATE POLICY "Profiles: users read own"
ON public.profiles
FOR SELECT
USING (auth.uid() = id);
DROP POLICY IF EXISTS "Profiles: users update own" ON public.profiles;
CREATE POLICY "Profiles: users update own"
ON public.profiles
FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- ============================================================================
-- 4. Suscripciones - Tabla + RLS por usuario
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  plan_id TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  user_role TEXT DEFAULT 'professional',
  updated_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Subscriptions: users read own" ON public.subscriptions;
CREATE POLICY "Subscriptions: users read own"
ON public.subscriptions
FOR SELECT
USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Subscriptions: users insert own" ON public.subscriptions;
CREATE POLICY "Subscriptions: users insert own"
ON public.subscriptions
FOR INSERT
WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Subscriptions: users update own" ON public.subscriptions;
CREATE POLICY "Subscriptions: users update own"
ON public.subscriptions
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- 5. syncra_entities (almacén híbrido) - Tabla + RLS por usuario
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.syncra_entities (
  type TEXT NOT NULL,
  key TEXT NOT NULL,
  user_id UUID NOT NULL,
  data JSONB,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (type, key, user_id)
);
ALTER TABLE public.syncra_entities ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Entities: users read own" ON public.syncra_entities;
CREATE POLICY "Entities: users read own"
ON public.syncra_entities
FOR SELECT
USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Entities: users upsert own" ON public.syncra_entities;
CREATE POLICY "Entities: users upsert own"
ON public.syncra_entities
FOR INSERT
WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Entities: users update own" ON public.syncra_entities;
CREATE POLICY "Entities: users update own"
ON public.syncra_entities
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- Índices recomendados para rendimiento
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_f931_historial_cuit_periodo
ON public.f931_historial (empresa_cuit, periodo_anio, periodo_mes);

-- Comentario: La referencia foreign key a auth.users a veces requiere permisos especiales
-- Si falla, se puede omitir la FK explícita, pero es recomendable:
-- ALTER TABLE public.ocr_usage_logs ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES auth.users(id);
