android {
    namespace "com.elevar.syncra_arg"
    compileSdkVersion 36
    ndkVersion "27.0.12077973"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    defaultConfig {
        applicationId "com.elevar.syncra_app"
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion 36
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    // Definimos las variables que Codemagic inyecta
    signingConfigs {
        release {
            storeFile file(System.getenv("FNC_KEYSTORE") ?: "no_hay_keystore")
            storePassword System.getenv("FNC_KEYSTORE_PASSWORD")
            keyAlias System.getenv("FNC_KEY_ALIAS")
            keyPassword System.getenv("FNC_KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            // ELIMINADO EL IF/ELSE: Ahora o firma bien, o el build falla.
            signingConfig signingConfigs.release
            
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
